### ISSUE TITLE
Possibility to support CocoaPods, Swift Package Manager?

### ISSUE THREAD

**Issue by the-freshlord** [bendodson/MonthYearPickerView-Swift#10]
Hello, 

I was wondering if making this available on CocoaPods or Swift Package Manager would be possible. I could make a PR for you if needed.

**Comment by davidseek** [comment]
Pod for literally 1 file drop in?

**Comment by bendodson** [comment]
As above, this is one file so I'm not going to add it to dependency managers. If your workflow requires your 3rd party code to be placed in a dependency manager then you can fork the project and use your private repo for that purpose.
