### ISSUE TITLE
cant show printed message

### ISSUE THREAD

**Issue by lwirasatria99** [bendodson/MonthYearPickerView-Swift#15]
Do you know why it doesnt work ?

**Comment by chriswilson1982** [comment]
What do you mean that you can’t show a printed message? What are you trying to achieve?

**Comment by Khushtar786** [comment]
Hii there,
Actually, I'm facing a problem date picker is not showing on click of a button in swift 4,5, Please Suggest something

**Comment by bendodson** [comment]
Original issue - No idea what is being asked. Would need to see a code sample to say why the printed message isn't displaying.

@Khushtar786 To show this from a button you need to do it the same as you would for a normal UIPickerView so you could have it on the page but show / hide it with the button, have it attached as an `inputView` on a UITextField that is hidden and have the button make the text field become the first responder, or embed it in the view of a view controller and present it with a UIPopoverPresentationController if running on iPad.

**Comment by Khushtar786** [comment]
> Original issue - No idea what is being asked. Would need to see a code sample to say why the printed message isn't displaying.
> 
> @Khushtar786 To show this from a button you need to do it the same as you would for a normal UIPickerView so you could have it on the page but the show / hide it with the button, have it attached as an `input view's on a UITextField that is hidden and have the button make the text field become the first responder, or embed it in the view of a view controller and present it with a UIPopoverPresentationController if running on iPad.

Thanks for the reply  I will look into this :)
