### ISSUE TITLE
Need instruction for integrating with SwiftUI

### ISSUE THREAD

**Issue by PMTool247** [bendodson/MonthYearPickerView-Swift#19]
The package is exactly what I'm looking for. However, as a new comer to SwiftUI, it's taken me a bit of time to make it available as a SwiftUI view. I'm still trying to figure out how to hook into onDateSelected(). Currently, I'm using `.onAppear()` for that, but it seems a like a hack. Would you please add instruction for doing that? I think that'll be of great help to other new SwiftUI developers as well.

**Comment by RyanSimcoxCSCI** [comment]
I also stumbled upon this package today and can't figure out how to actually use it in a Text field in SwiftUI.

**Comment by bendodson** [comment]
This is a UIKit project so if you wanted to embed it into SwiftUI you'd need to use `UIViewRepresentable` which allows you to use UIKit components in SwiftUI. It should be fairly straightforward if you just want the picker on screen but if you want to use it as a keyboard replacement for a `TextField` then you'd need to also make a custom UIKit `UITextField` which integrates with the picker as SwiftUI `TextField` does not have a way to use custom views as keyboards as far as I'm aware. I was able to find a [gist](https://gist.github.com/diamantidis/061d101853f6400f76780345614b2c90?permalink_comment_id=3441816) that demonstrates how to do this with a `UIPickerView` and the concept would apply equally well to `MonthYearWheelPicker`.

However, a better option would be to just rebuild this project in SwiftUI as it's far easier! That would look something like this:

```
struct MonthYearPickerView: View {
    @Binding var selectedMonth: Int
    @Binding var selectedYear: Int
    private var minimumDate: Date
    private var maximumDate: Date
    private var months: [String]
    private var years: [Int] = []
    
    private var availableYears: [Int] {
        let minYear = Calendar.current.component(.year, from: minimumDate)
        let maxYear = Calendar.current.component(.year, from: maximumDate)
        return Array(minYear...maxYear)
    }
    
    init(minimumDate: Date, maximumDate: Date, selectedMonth: Binding<Int>, selectedYear: Binding<Int>) {
        self.minimumDate = minimumDate
        self.maximumDate = maximumDate
        self._selectedMonth = selectedMonth
        self._selectedYear = selectedYear
        self.months = Calendar.current.monthSymbols.map { $0.capitalized }
        self.years = availableYears
    }
    
    var body: some View {
        HStack {
            Picker("Month", selection: $selectedMonth) {
                ForEach(1...12, id: \.self) { month in
                    Text(self.months[month - 1]).tag(month)
                }
            }
            .pickerStyle(WheelPickerStyle())
            
            Picker("Year", selection: $selectedYear) {
                ForEach(availableYears, id: \.self) { year in
                    Text(verbatim: "\(year)").tag(year)
                }
            }
            .pickerStyle(WheelPickerStyle())
        }
        .onChange(of: selectedMonth) {
            guard let date = DateComponents(calendar: Calendar.current, year: selectedYear, month: selectedMonth, day: 1, hour: 0, minute: 0, second: 0).date else { return }
            if date < minimumDate {
                selectedYear = Calendar.current.component(.year, from: minimumDate)
                selectedMonth = Calendar.current.component(.month, from: minimumDate)
            } else if date > maximumDate {
                selectedYear = Calendar.current.component(.year, from: maximumDate)
                selectedMonth = Calendar.current.component(.month, from: maximumDate)
            }
        }
    }
}
```

You would then use it like this:

```
struct ContentView: View {
    
    @State private var selectedMonth: Int = Calendar.current.component(.month, from: Date())
    @State private var selectedYear: Int = Calendar.current.component(.year, from: Date())
    
    var body: some View {
        VStack {
            MonthYearPickerView(minimumDate: Date(), maximumDate: Calendar.current.date(byAdding: .year, value: 15, to: Date())!, selectedMonth: $selectedMonth, selectedYear: $selectedYear)
                .onChange(of: selectedMonth) {
                    printDate()
                }
                .onChange(of: selectedYear) {
                    printDate()
                }
        }
    }
    
    private func printDate() {
        let string = String(format: "%02d/%d", selectedMonth, selectedYear)
        print(string)
    }
}
```

I've just whipped this up in 5 minutes this morning so no guarantees on how well it works, etc, but should at least be enough of a starting off point for you to integrate something similar in your own project but I have no plans to port this project over to SwiftUI beyond this code sample.

**Comment by PMTool247** [comment]
@bendodson, thank you for the code and suggestion.

About my question concerning a way to connect to `.onDateSelected` handler, I was able to get it working by using the `.set()` modifier
```
let picker = MonthYearWheelPicker().set(\.onDateSelected, to: {month, year in
  print("onDateSelected: Called")
})
```
